---
version: "3"
volumes:
        myapp:
services:
        docer_prod:
                volumes:
                        - myapp:/myapp/target/
                build: docker_prod/
        docker_web:
                volumes:
                        - myapp:/usr/local/tomcat/webapps/
                image: tomcat:latest
                command: "/usr/local/tomcat/bin/catalina.sh run"
                ports:
                        - "8080:8080"

